-- Generated by LitLua (https://www.github.com/jwtly10/litlua) v0.0.2
-- AbsSource: /var/folders/8r/rkbmn5qd68jfvl9t6sn0szym0000gn/T/transformer-test-4122916532/basic.md
-- Generated: 2024-01-01T00:00:00Z

-- WARNING: This is an auto-generated file.
-- Do not modify this file directly as changes will be overwritten on next compilation.
-- Instead, modify the source markdown file and recompile.

local name = "Hello World"
print(name)

foo = 1 + 2
print(foo)

local _ = b

local y = 5

local a = y
print(a)

-- Bar is a function that adds two numbers
--
-- @param a number
--
-- @param b number
--
-- @return number sum of a and b
Bar = function(a, b)
    return a + b
end

-- You can go to definition of bar by clicking on it
print(Bar(10, 11))

-- try typing B in this print function and see the completion
print(...)

