package litlua

import (
	"fmt"
	"github.com/stretchr/testify/require"
	"strings"
	"testing"
	"time"
)

func TestCanWriteGenHeaders(t *testing.T) {
	d := Document{
		Metadata: MetaData{
			Source: "test.md",
		},
	}

	var output strings.Builder
	w := NewWriter(&output)

	now := time.Now()

	if err := w.Write(&d, now); err != nil {
		t.Fatalf("Error writing document: %v", err)
	}

	expected := fmt.Sprintf(`-- Generated by LitLua (https://www.github.com/jwtly10/litlua) v0.0.1
-- Source: %s
-- Generated: %s

-- WARNING: This is an auto-generated file.
-- Do not modify this file directly as changes will be overwritten on next compilation.
-- Instead, modify the source markdown file and recompile.

`, "test.md", now.Format(time.RFC3339))
	require.Equal(t, expected, output.String())
}
