-- Generated by LitLua (https://www.github.com/jwtly10/litlua) v0.0.1
-- Source: testdata/extract/partial_src.md
-- Generated: 2024-01-01T00:00:00Z

-- WARNING: This is an auto-generated file.
-- Do not modify this file directly as changes will be overwritten on next compilation.
-- Instead, modify the source markdown file and recompile.

-- Leader key
vim.g.mapleader = " "

-- Quick save
vim.keymap.set('n', '<leader>w', ':w<CR>')



